### ISSUE TITLE
Broken Instance generation for Vision

### ISSUE THREAD

**Issue by dkales** [KULeuven-COSIC/Marvellous#4]
The constructor of the Vision class references the variable `n`, which is undefined, probably should be `nm` at these points.
https://github.com/KULeuven-COSIC/Marvellous/blob/1bad94a239dd52f7206cd7f2d3a7f023e006f533/instance_generator.sage#L8
https://github.com/KULeuven-COSIC/Marvellous/blob/1bad94a239dd52f7206cd7f2d3a7f023e006f533/instance_generator.sage#L9
https://github.com/KULeuven-COSIC/Marvellous/blob/1bad94a239dd52f7206cd7f2d3a7f023e006f533/instance_generator.sage#L16

Furthermore, the assert for the state size being as large as the security level actually prevents the generation of the Vision Mark I instances from the [paper](https://eprint.iacr.org/2019/426.pdf), Appendix D.1 having 192 and 256 bit security.

`vision_instance = Vision(s = 192, nm = 128, m = 16)`
`vision_instance = Vision(s = 256, nm = 128, m = 16)`

Are these intended to be m = 24 and 32 instead?

**Comment by siemen11** [comment]
Thank you for noticing this! I adapted the parameters n.
We are currently looking into the Mark I instances.

**Comment by siemen11** [comment]
We removed Mark I instances in the ePrint with higher security than state size. We never explained in the article how to handle a bigger key compared to the state size of the block cipher. We hope this does not inconvenience you. If we can help with your application in another way, please let us know. The software will remain unchanged with respect to this.

**Comment by dkales** [comment]
Alright, thanks for taking a look!
